[build]
  # Use plain pnpm build so Netlify runs the root package script reliably.
  # If your Netlify environment still treats this as a workspace you can
  # switch to: pnpm --filter . build
  command = "pnpm build"
  publish = "."

[context.production.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
