[build]
  # Use plain pnpm build so Netlify runs the root package script reliably.
  # If your Netlify environment still treats this as a workspace you can
  # switch to: pnpm --filter . build
  command = "pnpm build"
  publish = "."

[context.production.environment]
  # Next 16 requires Node >= 20.9.0 — set Netlify's Node to a compatible version
  NODE_VERSION = "20.9.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
